### ISSUE TITLE
Add support for generating optionality based on the maven dependency configuration

### ISSUE THREAD

**Issue by knrc** [CycloneDX/cyclonedx-maven-plugin#314]
The current codebase derives the scope of a component through bytecode analysis, however this has problems in that it
- differs from maven's view of what is optional (non-intuitive)
- can change depending on which projects have been built (classes need to exist)
- doesn't handle artifact relocations

We would like the ability to define optionality based on whether maven determines the artifact to be optional, i.e. through the dependency resolution process rather than bytecode inspection.

@hboutemy I have something working for this, just waiting on the conclusion of #306 and for other PRs to be submitted.

@norrisjeremy FYI

**Comment by hboutemy** [comment]
Maven optional is a boolean with one semantics = https://maven.apache.org/ref/3.9.1/maven-model/maven.html#class_dependency
CycloneDX optional is one value of scope with different semantics = https://cyclonedx.org/docs/1.4/json/#components_items_scope
(and i won't explain about Maven scopes which are a completely different thing)

each time we use a term, we must clarify in which world we refer to#312 

but yes, the way SBOM scope=optional detection has been implemented in #65 does not make me feel that it's the usually expected behaviour
