### ISSUE TITLE
Which version of plugin matches Maven 3.0?

### ISSUE THREAD

**Issue by evlissa** [CycloneDX/cyclonedx-maven-plugin#411]
Hello!

Could you please help me to find out which version of plugin will correctly work with Maven 3.0?

Getting an error like this every time with different versions:
`Failed to execute goal org.cyclonedx:cyclonedx-maven-plugin:2.5.3:makeAggregateBom (default) on project test-parent: The plugin org.cyclonedx:cyclonedx-maven-plugin:2.5.3 requires Maven version 3.1`

I couldn't find any information about correlation between maven versions and cyclonedx plugin versions

**Comment by hboutemy** [comment]
Maven 3.1 prerequisite is there since CycloneDX Maven Plugin 2.0.0
1.6.8 does not define any prerequisite, perhaps it will accept to run, but I don't know what content will such an old release generate: you will definitively be on your own with this

notice that Maven 3.0 itself is really old and EOL https://maven.apache.org/docs/history.html
I suppose you have good reasons not to upgrade, but I can't resist advising to upgrade: if it's the JVM release that blocks you, Maven 3.1.1 run with JDK 5 like 3.0

it's hard to do new work with old tools like that
