### ISSUE TITLE
Allow extending the generated SBOM

### ISSUE THREAD

**Issue by vy** [CycloneDX/cyclonedx-maven-plugin#414]
CycloneDX SBOM spec has various capabilities (e.g., [VEX](https://cyclonedx.org/capabilities/vex/), [VDR](https://cyclonedx.org/capabilities/vdr/)) that are not implemented by the `cyclonedx-maven-plugin` yet. Some doesn't fit as a use case (hence, will probably never be implemented) and some simply needs a developer. Though it would be extremely convenient if the plugin would have allowed extending the generated model.

I would like to discuss how could such extension points be realized. To get it started, below I share some suggestions:

### Merging the user-provided JSON literal

In this approach, the user provided JSON is parsed into an `Object` (via Jackson?) and added to the root of the BOM model with key `vulnerabilities`:

```
<plugin>
  <groupId>org.cyclonedx</groupId>
  <artifactId>cyclonedx-maven-plugin</artifactId>
  <configuration>
    <extensions>
      <extension>
        <key>vulnerabilities</key>
        <format>JSON</format>
        <content><![CDATA[
          [
            {
              "id": "CVE-2020-25649",
              "source": {
                "name": "NVD",
                "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-25649"
              },
              "references": ...,
              "ratings": ...,
              ...
            }
          ]
        ]]></content>
      </extension>
    </extensions>
  </configuration>
</plugin>
```

Note that since `c-m-p` parses and injects this value into the eventual SBOM model, it should be rendered not only for `target/bom.json`, but also for `target/bom.xml`.

### Merging the user-provided XML block

Similar to the above, but using XML instead:

```
<plugin>
  <groupId>org.cyclonedx</groupId>
  <artifactId>cyclonedx-maven-plugin</artifactId>
  <configuration>
    <extensions>
      <extension>
        <key>vulnerabilities</key>
        <!-- `format` is not needed, since it obviously defaults to XML -->
        <content>
          <vulnerability>
            <id>CVE-2020-25649<id>
            <source>
              <name>NVD</name>
              <url>https://nvd.nist.gov/vuln/detail/CVE-2020-25649</url>
            </source>
            <!-- ... -->
          </vulnerability>
        </content>
      </extension>
    </extensions>
  </configuration>
</plugin>
```

### Note on merging strategy

Extension clearly brings up the merging strategy issue. What shall happen if the key and/or value already exists? How shall one describe the entry points lower down the root? etc. To keep things simple, at first iteration, we can only allow extending root keys where the merging strategy is simple: override.

### Note on spec validation

Ideally the eventual spec should be validated against XML/JSON schemas. I would prefer to have this in the first iteration of this feature to help users avoid shooting themselves in the foot.

### Note on aggregation

How should such extensions be aggregated at the parent level? If multiple [Maven] modules provide extensions with overlapping keys/content, how one shall merge them? I would leave this question for later by simply not aggregating extensions in the first iteration.

**Comment by hboutemy** [comment]
@vy @ppkarwasz let's try to focus on your VEX and VDR examples first, keeping in mind that it eventually can be later implemented as a generic "add any data to the CDX content generated by `cyclonedx-maven-plugin` based on POM content"

[VEX](https://cyclonedx.org/capabilities/vex/) and [VDR](https://cyclonedx.org/capabilities/vdr/) introduction explain how they can be used in 2 ways:
1. Independent BOM and VEX or VDR BOM
2. BOM with embedded VEX or VDR data

@vy @ppkarwasz IIUC, you maintain independent VEX and VDR BOMs on the log4j website (if you can share urls, please) = it looks like option 1, where the BOM will be done by `cyclonedx-maven-plugin`
IIUC, you don't really want to do option 2 = embed the VEX and VDR data into the BOM generated by `cyclonedx-maven-plugin`, because this BOM will be published to Maven Central, where it is immutable, contrary to VEX and VDR nature
and finally, IIUC, what you'd like is to have the (immutable) BOM published to Maven Central contain an external reference to your VEX and VDX BOMs maintained on your site: that would permit users to discover them from the BOM on Maven Central

are my 3 points correct?

**Comment by ppkarwasz** [comment]
@hboutemy,

Yes, we don't want to use option 2, since Maven Central files are immutable. We want to add a link to a CycloneDX file hosted on our webpage. We didn't agree on its contents, but it will look like:
 * https://logging-log4j2.staged.apache.org/log4j/vdr.cyclonedx.xml
 * https://logging-log4j2.staged.apache.org/log4j/vdr.cyclonedx.json
 
 The most important part of the content is the `serialNumber` that will always stay the same, while we will change the content and increase `version`.

We might take advantage of content negotiation, but it is currently not working:
```
curl -i https://logging-log4j2.staged.apache.org/log4j/vdr -H 'Accept: application/vnd.cyclonedx+xml'
```

Nevertheless we'll probably need to be able to add multiple URLs to the VDR and VEX files (and maybe a `bom-ref` containing the serial number).

**Comment by hboutemy** [comment]
@ppkarwasz I'm a little bit lost: what makes these files as "VDR"? how do you expect them to be different from what is generated by `cyclonedx-maven-plugin`?

I have the same question for "VEX"

**Comment by ppkarwasz** [comment]
@hboutemy,

The examples are pretty much work in progress. As far as I understand we will be filling a `<vulnerabilities>` element, when problems arise and reference the components that are already present in the file.

**Comment by vy** [comment]
I think both parties are not on the same page. I will try to sum things up to clarify.

### VEX-vs-VDR

As far as I understand, CycloneDX VEX and VDR schema are identical, they only differ in purpose. They both need to comply with the one-and-only [CycloneDX specification](https://cyclonedx.org/specification/overview/). In practice, they can be implemented by means of `vulnerabilities` entries defined in the specification.

### What does make a file a CycloneDX VDR/VEX?

A CycloneDX VEX/VDR file must implement the `vulnerabilities` defined by the [CycloneDX specification](https://cyclonedx.org/specification/overview/).

### Where is VEX/VDR located?

VEX/VDR can either be embedded into the SBOM or referred from an SBOM using `externalReferences`. I created #414 for the former approach, though we changed our course to the latter. Let me repeat:

1. **We don't want to extend the generated SBOM with `vulnerabilities` anymore** – hence, the title/goal of this ticket is misleading.
2. **We want to extend the generated SBOM with extra `externalReference` entries.**

### What about VEX/VDR files hosted on `logging-log4j2.staged.apache.org`?

@ppkarwasz has created and uploaded them to get the point across. They don't represent the final state. Though they simply demonstrate _"a"_ XML/JSON resource we want to link to in the SBOM generated by the `cyclonedx-maven-plugin`.

**Comment by hboutemy** [comment]
thanks @vy , that one I better understand
@stevespringett , is there a preferred id for an external reference to a VEX/VDR url?

@vy @ppkarwasz I just found back one interesting experience I saw in the past: Solr publication of VEX https://solr.apache.org/security.html#vex
I don't know if they publish a an SBOM with all they releases, that would have a reference to this VEX: but IIUC, that's what you want to do

**Comment by stevespringett** [comment]
> is there a preferred id for an external reference to a VEX/VDR url?

If its a URL, then no, no preferred id.

**Comment by hboutemy** [comment]
thank you @stevespringett 
do you know other organisation using VEX/VDR, like Apache Solr? Sharing concrete examples would help projects learn how to implement

**Comment by vy** [comment]
After a video call with @ppkarwasz, @stevespringett, @hboutemy, and me on 2023-11-03T16:00 (CET), we decided to drop this request in favor of a simpler approach described in #421.
