### ISSUE TITLE
Missing CPEs in generated BOM

### ISSUE THREAD

**Issue by aland404** [CycloneDX/cyclonedx-maven-plugin#67]
All the components in my generated BOM have a correct PURL field but no one has a CPE information.

Since the dependency track software internal analyzer makes use of the Common Platform Enumeration (CPE) defined in components and only Components with a valid CPE will be evaluated with this analyzer, DT does not found any vulnerability in my dashboard.

Is there a way for forcing the mvn CycloneDX:makeBom command to fill the CPE field ?

**Comment by stevespringett** [comment]
CPE's are centralized and cannot be programmatically determined in advance without the assistance of a large dataset that maps components to CPEs.

Refer to https://cyclonedx.org/use-cases/#known-vulnerabilities for guidelines on what fields to use for identifying vulnerabilities in various forms of software.

You're likely not seeing results in DT due to OSS Index not being enabled. Refer to https://docs.dependencytrack.org/FAQ/

**Comment by aland404** [comment]
Thanks for your quick answer.

I had enabled OSS Index but there was a mistake in my credentials, however the UI (green text-fields) and the docker logs (Sonatype OSS Index analysis complete) do not feed this error back. An improvement on it could be fine, but the problem is not with the cyclonedx-maven-plugin.

Anyway, i can now see vulnerabilities on my project, this is great.

For the CPEs, does it mean we cannot enjoy the "Precise matching via NVD" vulnerability intelligence withtout any external tool (or internal dev) to map CPEs to components ? Though it does not appear to be a problem thus OSS index also seems to be fed with NVD.

Thanks again for your help.

**Comment by stevespringett** [comment]
CPEs are specifically designed to describe operating systems, applications, and hardware devices. The spec only supports these things. It was never designed to describe libraries although CPE is being misused by the NVD to describe them using 'application'.

Due to the centralization of CPE and CNAs, it's not possible to include them without the assistance of an external mapping service. In a sense, OSS Index performs transparent Package URL to CPE mapping behind the scenes. This is obviously not an accurate representation of what OSS Index actually does, but at a high level, that's what it achieves. If a publically available mapping source ever becoming a reality, then it may be possible to include CPE. However, keep in mind that CPE is deprecated by the NVD and by CycloneDX. Once the NVD releases details about their strategy and roadmap for how they will support SWID tagIDs as a replacement for CPE, then it may be possible to automatically include tagIDs, but we'll have to wait for the NVD to release details.

**Comment by aland404** [comment]
Thank you for your quick and detailed answer, i close my comment.
