### ISSUE TITLE
make generated bom.xml and bom.json reproducible

### ISSUE THREAD

**Issue by hboutemy** [CycloneDX/cyclonedx-maven-plugin#84]
cyclonedx-maven-plugin build has been made reproducible, which is perfect to check binary from source: https://github.com/jvm-repo-rebuild/reproducible-central#org.cyclonedx:cyclonedx-maven-plugin

but `bom.xml` and `bom.json` files that are published along the source and binary artifacts are not reproducible, see diffoscope result https://github.com/jvm-repo-rebuild/reproducible-central#org.cyclonedx:cyclonedx-maven-plugin
- they contain a timestamp: using build timestamp used for the jars should do the job
- generated serial number is not reproducible
- bom.json has much missing content

**Comment by stevespringett** [comment]
The serial number is a UUID and is not predictable nor reproducible. This is by design as all SBOMs require a unique serial number per OWASP SCVS and NTIA guidance. Having two SBOMs that just so happen to have identical content does not make them the same, therefore unique serial numbers are required.

Serial number can be omitted if this is a problem. The Maven plugin allows you to disable serial number generation.

I'd recommend altering the timestamp if this is concern. The CycloneDX object model is intentionally simplistic to allow for progressive enhancement of the SBOM throughout the build pipeline. Overwriting the timestamp with a value that is not an accurate representation of the current time does not align to the facts-first values of the project. The other option is to generate CycloneDX v1.1 SBOMs instead of v1.2, since v1.1 does not include the metadata section.

Not sure what is meant by bom.json is missing content.

**Comment by hboutemy** [comment]
Using Reproducible Build timestamp is just a choice: it's easy to update the plugin to detect and use it.
But if UUID is not intended to be reproducible, using reproducible timestamp is not really useful.

It's sad that UUID is the only data that is not reproducible at all: instead of being random, can't it be based on a fingerprint? eventually a fingerprint based on SBOM content + GAV of the project?

Having a reproducible SBOM would IMHO be a useful feature.

Waiting for that, I just added a parameter to artifact:buildinfo to ignore generated SBOM, given they are not intended to be reproducible for now

**Comment by stevespringett** [comment]
Reproducible builds cripple forensic capabilities. If the software concerns public safety, critical infrastructure, or national security, I would not recommend this approach. It would also violate OWASP SCVS principals.

**Comment by hboutemy** [comment]
it's a choice I respect: I switched myself from putting timestamps everywhere for tracking every build result to remove everything with Reproducible Builds, I know that each approach has pros and cons
I won't force: you can choose to close this issue as "won't fix" or let open to reevaluate sometime later, no problem for me

**Comment by hboutemy** [comment]
closing this request, even if there are new ones #226
